services:
  qdrant:
    image: "qdrant/qdrant:latest"
    container_name: qdrant_vector
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - local-net

  prometheus:
    image: "prom/prometheus:latest"
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - local-net
    volumes:
      - /mnt/d/LEARN_AI/SpringAI/springai/SpringAI_RAG/prometheus-config.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: "grafana/grafana:latest"
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - /mnt/d/LEARN_AI/SpringAI/grafana-data:/var/lib/grafana
    networks:
      - local-net

  jaeger:
    image: "jaegertracing/all-in-one:latest"
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - local-net

volumes:
  grafana-data:

networks:
  local-net:
    external: true
